import Link from "next/link";
import "./globals.scss";
import LayoutLogin from "./layoutLogin";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    let session = await getServerSession(authOptions);

    return (
        <html lang="en">
            <body>
                <div className="nav flex justify-center items-center">
                    <Link href="/">
                        <h2>MYFORUM</h2>
                    </Link>
                    <Link href="/list">LIST</Link>
                    <Link href="/write">WRITE</Link>
                    <Link href="/register">REGISTER</Link>
                    <div className="mx-5  font-bold border-solid rounded-sm">
                        {session == null
                            ? null
                            : session.user.name}
                    </div>
                    <LayoutLogin session={session} />
                </div>
                {children}
            </body>
        </html>
    );
}
